### ISSUE TITLE
Update to 3.3

### ISSUE THREAD

**Issue by nikpap** [DigiDago/moodle-course_modulenavigation#20]
Removed 'numsections' from topics and weeks formats : 

https://tracker.moodle.org/browse/MDL-57769

**Comment by clementpr** [comment]
Mettre à jour le plugin avec 

1. Mise à jour du fichier https://github.com/DigiDago/moodle-course_modulenavigation/blob/master/version.php >>> $plugin->release    = '3.6'; + date mise à jour


2. Mise à jour du fichier  https://github.com/DigiDago/moodle-course_modulenavigation/blob/master/changes.md
Version 3.6 (2017.XX.XX) 
1. Check and update to moodle version 3.3 
2. Update plugin for MDL-57769 - Course formats: Attribute 'numsections' was removed from topics and weeks, other course formats may want to implement similar changes
3. ??
