### ISSUE TITLE
Integrate July Bas changes

### ISSUE THREAD

**Issue by nikpap** [DigiDago/moodle-course_modulenavigation#25]

**Comment by clementpr** [comment]
https://github.com/bmbrands/moodle-block_course_modulenavigation/commit/43aadf3bb832a7fdd3619cfd2773a072c11868d8
https://github.com/bmbrands/moodle-block_course_modulenavigation/commit/b1381791ecc01e100f9ef7c5eef00a69ad8907d5
https://github.com/bmbrands/moodle-block_course_modulenavigation/commit/c15024560d3c3f1b8428af6b7bf2cc305531ce1c
