### ISSUE TITLE
Ajouter sommaire de cours par défaut dans toutes pages de cours 

### ISSUE THREAD

**Issue by clementpr** [DigiDago/moodle-course_modulenavigation#27]
Voir si config.php permet de le faire. 

//
// You can specify a different class to be created for the $PAGE global, and to
// compute which blocks appear on each page. However, I cannot think of any good
// reason why you would need to change that. It just felt wrong to hard-code the
// the class name. You are strongly advised not to use these to settings unless
// you are absolutely sure you know what you are doing.
//      $CFG->moodlepageclass = 'moodle_page';
//      $CFG->moodlepageclassfile = "$CFG->dirroot/local/myplugin/mypageclass.php";
//      $CFG->blockmanagerclass = 'block_manager';
//      $CFG->blockmanagerclassfile = "$CFG->dirroot/local/myplugin/myblockamanagerclass.php";
//

**Comment by nikpap** [comment]
Je crois que c'est déjà fait, non ?

https://github.com/DigiDago/moodle-install/blob/master/editblocks.php
