### ISSUE TITLE
& (esperlette)dans le titre affiche du code html à la place de "&"

### ISSUE THREAD

**Issue by clementpr** [DigiDago/moodle-course_modulenavigation#28]
Reproduire bug  

1. Ajouter 3 activités / ressources dans un cours
2. AJouter le block sommaire de cours
3. AJouter un "&" dans un titre d'activité/ressource

![image](https://user-images.githubusercontent.com/8448884/31607887-7eba3302-b26e-11e7-943a-5980bba58453.png)

(généralement quelque chose comme :  
<balise><?php echo format_string($COURSE->fullname); ?></balise>)

**Comment by CrymSonir** [comment]
Problème d'encodage du caractère certainement , je pense qu'on va observer la même chose pour d'autre caractères "spéciaux".
